version: "2"

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /home/karthik/Experimental/knowledgehub/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    #    network_mode: "host"
    restart: always



  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000